# Generated by Django 3.1.4 on 2021-06-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_radiofeedbacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiofeedbacks',
            old_name='desc',
            new_name='rdesc',
        ),
        migrations.RenameField(
            model_name='radiofeedbacks',
            old_name='name',
            new_name='rname',
        ),
    ]
